baseURL: "https://RachelZLei.github.io/RachelLei/"

title: Rachel Lei
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Courses
          url: courses/
          weight: 1

        - name: Projects
          url: projects/
          weight: 2

        - name: Blog
          url: blog/
          weight: 3

        - name: CV
          url: /RachelLei/cv.pdf
          weight: 4

params:
    hideFooter: true
    description: "Personal website of Rachel Lei — projects, courses, and notes in Data Science & ML."
    author: Rachel Lei
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","blog","courses"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zhiyao(Rachel) Lei
          subtitle: "I'm currently a third-year BSc student in Econometrics and Data Science at Universiteit van Amsterdam, with a solid background in statistics and programming (Python, R, and Stata). While I've covered the fundamentals, my true passion lies in machine learning and computational algorithms. I'm keen to explore data science research roles that involve both theoretical inquiry and practical application."
          imageUrl: "picture.JPG"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Courses
              url: courses/
            - name: Projects
              url: projects/
            - name: Blog
              url: blog/
            - name: CV
              url: /cv.pdf
 
    socialIcons:
      - name: Email
        url: "mailto:leizhiyao2005@gmail.com"
      - name: GitHub
        url: "https://github.com/RachelZLei"
      - name: Kaggle
        url: "https://www.kaggle.com/rachellei918"
      - name: LinkedIn
        url: "https://www.linkedin.com/in/zhiyao-lei-9a40b22b1/"

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rachel Lei"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2